micronaut:
  application:
    name: hero
  server:
    cors:
      enabled: true
      configurations:
        web:
          allowedOrigins: ${ALLOWED_ORIGIN:``}
          allowedMethods:
            - OPTIONS
            - GET
            - POST
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
datasources:
  default:
    url: ${DATABASE_URL:`jdbc:postgresql://localhost:5432/hero_votes`}
    username: ${DATABASE_USER:`hero`}
    password: ${DATABASE_PASSWORD:`hero`}
jpa:
  default:
    entity-scan:
      packages:
        - 'dc.vilnius.kudos.domain'
    properties:
      hibernate:
        bytecode:
          provider: none
        hbm2ddl:
          auto: none
flyway:
  datasources:
    default:
      enabled: true
supabase:
  url: ${SUPABASE_URL:`n\a`}
  api-key: ${SUPABASE_API_KEY:`n\a`}
  token-endpoint: ${SUPABASE_TOKEN_URL:`/auth/v1/token?grant_type=password`}
