micronaut:
  application:
    name: hero
  server:
    port: ${PORT:8080}
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
datasources:
  default:
    url: ${DATABASE_URL:`jdbc:postgresql://localhost:32770/hero_vote`}
    username: ${DATABASE_USER:`hero`}
    password: ${DATABASE_PASSWORD:`hero`}
jpa:
  default:
    entity-scan:
      packages:
        - 'dc.vilnius.kudos.domain'
    properties:
      hibernate:
        bytecode:
          provider: none
        hbm2ddl:
          auto: none
flyway:
  datasources:
    default:
      enabled: true
